### ISSUE TITLE
Different versions of JALI rig

### ISSUE THREAD

**Issue by tcfu** [yzhou359/VisemeNet_tensorflow#1]
Hi Yang,

I have tried the JALI rig you provided but it didn't work. I wonder if you could specify the corresponding variables between the different versions? Thank you so much!

**Comment by yzhou359** [comment]
Hi, I'm trying to fix it. I was using a different JALI rig which is not available in public.

**Comment by liltak** [comment]
Hi Yang,
I have the same issue.

Is it possible for us to change the name of the variables on our own to fix the problem?
Let us know if the code is available!
Thanks in advance

**Comment by yzhou359** [comment]
Hi there, sorry for the delay. The code has been updated with suitable annotations. Feel free to play with it.

**Comment by liltak** [comment]
@yzhou359 
Thanks so much!!!

**Comment by drjinying** [comment]
Hi Yang,

In the Biwi annotation, the maya_param.csv files has 30 columns. Could you please share how does it map to the 22 columns you use for training? Or, what' the semantic meaning of the 30 columns? I saw you provided this info for the public model, it would be great if we have the same thing for the non-public one, so we can leverage your post processing code :)

Thanks in advance!

**Comment by yzhou359** [comment]
The maya_param.csv is actually not used in this project. It's just a more accurate annotation (with 30 control parameters) for the non-public model which could not be shared.
