### ISSUE TITLE
custom viseme

### ISSUE THREAD

**Issue by DevTech15** [yzhou359/VisemeNet_tensorflow#10]
Hi @yzhou359 thank you so much for sharing your work. i was trying to generate viseme with TTS. This repo is the Only resource i found on git related to viseme generation. But I think it is usable for only in a specific software. I was wondering if you could please help me in understanding the generated viseme and how can i get viseme which i can use according to my usecase. 
will really appreciate your comment.

**Comment by yzhou359** [comment]
Hi @AhmadManzoor , you are right - our implementation only works for the JALI face rig. If you download the JALI face rig, when you clip on the lips, you will see the viseme parameters on the top-right panel of the Maya. such as 'JALI.translateX', 'JALI.translateY', 'AAA', 'Eh', 'AHH', 'OHH', 'UUU', 'IEE', 'RRR', 'WWW', 'SSS', 'FFF', 'TTH', 'MBP', 'SSH', 'Schwa', 'GK', 'LNTD', etc.

**Comment by DevTech15** [comment]
thank you @yzhou359 for your reply. can you please walk me guide me on how can i generate viseme i.e 

>  'AAA', 'Eh', 'AHH', 'OHH', 'UUU', 'IEE', 'RRR', 'WWW', 'SSS', 'FFF', 'TTH', 'MBP', 'SSH', 'Schwa', 'GK', 'LNTD', etc.

from your script. because i believe your script is first generating these visemes then converting i to something that is usable in JALI. so after modifying a bit your script i think i can achieve my goal. i will really appreciate your guidance

**Comment by yzhou359** [comment]
@AhmadManzoor The output of our network are directly those viseme values used in maya and we use a script (maya_animation.py) to parse the output to animate the JALI model directly.
