### ISSUE TITLE
Using MFCC feature extraction default parameters will 

### ISSUE THREAD

**Issue by AquaskyCamus** [yzhou359/VisemeNet_tensorflow#2]
Hi, yzhou,

When trying to repro the test, I found the MFCC features are not correctly extracted when using the default mfcc parameters. The number of samples in each frame is 25ms x 44kHz = 1100 samples, which is greater than nfft=512. In this case the frame will be truncated. 

Did you down-sampled the wav file before sending it to mfcc feature extractor, or did you set nfft=2048 to avoid this happening?

Thanks.

**Comment by yzhou359** [comment]
We haven't noticed that problem yet - we just use that truncated version as our input data. It might get better results if down sampling the audio to 16k. Thanks for letting us know.

**Comment by AquaskyLucien** [comment]
Thanks yzhou. Down-sampling the wav file to 16k is a good choice so that the model can applied to most of the wav files without retraining.
