### ISSUE TITLE
Training code and JALI based annotations for training

### ISSUE THREAD

**Issue by g1910** [yzhou359/VisemeNet_tensorflow#3]
Hi

Is the training code available as part of this repository? Also is it possible to get access to the JALI based annotations that you created as part of training the model?

Thanks

**Comment by yzhou359** [comment]
The training code is still under preparing. The JALI based annotation dataset is available [here](https://www.dropbox.com/sh/oj13tvq9ggf2puz/AADBPyRUcyisFtKgCoDmNhLHa?dl=0). More details could be found [here](VisemeNet_Annotation_README.md).
