### ISSUE TITLE
Training_from_scratch

### ISSUE THREAD

**Issue by anasvaf** [yzhou359/VisemeNet_tensorflow#6]
Hello,
Thank you for providing your code to the paper!! Really appreciated it!
I would like to try to train the VisemeNet from scratch; meaning that I would have a directory of wav files for my input. Any advice on how should I use the train_visemenet.py?
Currenlty it takes as an argument one test file but I cannot get the script running for training.

**Comment by yzhou359** [comment]
We're sorry that we cannot provide the training code (commercial issue). But we're also working on another version with free license which may come later. Will announce it in the issue when it's ready.
