### ISSUE TITLE
Have any chance to get the training code.

### ISSUE THREAD

**Issue by adamlan001** [yzhou359/VisemeNet_tensorflow#7]
Hi, yzhou359
I am an animator and a Beginner amateur in AI technology ,
I'm very interested in VisemeNet_tensorflow project.
And I'm trying training my own speech animation data for VisemeNet, and JALI rig.
Is there any chance to get the training code to do this?

**Comment by yzhou359** [comment]
We're sorry that we cannot provide the training code (commercial issue). But we're also working on another version with free license which may come later. Will announce it in the issue when it's ready.
