### ISSUE TITLE
Question about pretrain for the first two stages

### ISSUE THREAD

**Issue by arxrean** [yzhou359/VisemeNet_tensorflow#9]
Hi! Thanks for sharing your code. I just have a simple question about the pretrain for the first two stages.

For example, the input size of the audio in the code is (1484, 65). It seems the output size of Phoneme groups and lankmarks are (1484, 21) and (1484, 76)? If so, how do you make the audio correspond to others one to one. I mean the audio actually corresponds to hundreds of video frames and each frame corresponds to one landmark. Do you duplicate frames to match the shape of the audio?

And why the output of Phoneme groups is (?, 21)? In the figure of the paper, the last channel of the output seems to be 20.

Thank you!

**Comment by yzhou359** [comment]
Hi, sorry for late reply. 
As you said, we represented the audio/phoneme/landmarks with the matrixes sharing the same first dim size, we map a window of audio matrix around frame t to the landmark/phoneme at frame t. e.g. the correspondence is audio[t-half_win_size:t+half_win_size] -> landmark/phoneme [t].  
There is another 'silence' group for the phoneme output.
